language: node_js
sudo: false
node_js:
  - 4
  - 6
  - 7
script:
  - "npm test"
  - "./node_modules/.bin/eslint ."
after_script:
  - "CODECLIMATE_REPO_TOKEN=9c89b2791d9aa6b8aefd9d1f8249604342ad56563a4f46036cb51ec85e7cde79 ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/jasmine-node --captureExceptions spec/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
